<div class="contenido">
    <div class="calendario">
        <header>
            <h2 id="mes">Abril</h2>
            <a class="btn-ant" id="btn-prev"><</a>
            <a class="btn-pro" id="btn-ant">></a>
        </header>
        <table>
            <thead>
                <tr>
                    <td>Dom.</td>
                    <td>Lun.</td>
                    <td>Mar.</td>
                    <td>Mie.</td>
                    <td>Jue.</td>
                    <td>Vie.</td>
                    <td>Sáb.</td>
                </tr>
            </thead>
            <tbody id="dias">
                <tr>
                    <td>1</td>
                    <td>2</td>
                    <td>3</td>
                    <td>4</td>
                    <td>5</td>
                    <td>6</td>
                    <td>7</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>2</td>
                    <td>3</td>
                    <td>4</td>
                    <td>5</td>
                    <td>6</td>
                    <td>7</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>2</td>
                    <td>3</td>
                    <td>4</td>
                    <td>5</td>
                    <td>6</td>
                    <td>7</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>2</td>
                    <td>3</td>
                    <td>4</td>
                    <td>5</td>
                    <td>6</td>
                    <td>7</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>2</td>
                    <td>3</td>
                    <td>4</td>
                    <td>5</td>
                    <td>6</td>
                    <td>7</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>2</td>
                    <td>3</td>
                    <td>4</td>
                    <td>5</td>
                    <td>6</td>
                    <td>7</td>
                </tr>
            </tbody>            
        </table>
        <footer>
            <h2 id="ano">2020</h2>
        </footer>        
    </div>
</div>
